import * as grpc from '@grpc/grpc-js';
import { AddDataSourceRequest, AddDataSourceResponse, DeleteDataSourceRequest, DeleteDataSourceResponse, GetDataSourcesRequest, GetDataSourcesResponse, VerifyConfigRequest, VerifyConfigResponse } from './szconfig/szconfig_pb';
import { SzConfigClient } from './szconfig/szconfig_grpc_pb';
import { SzConfig } from './abstracts/szConfig';
import { newException } from './szHelpers';
import { SzError, SzNoGrpcConnectionError } from './senzing/SzError';
import { ADD_DATASOURCE_RESPONSE } from './types/szConfig';
import { DEFAULT_CONNECTION_STRING, DEFAULT_CREDENTIALS, DEFAULT_CHANNEL_OPTIONS, DEFAULT_CONNECTION_READY_TIMEOUT, SzGrpcEnvironmentOptions } from './szGrpcEnvironment';
import { SzGrpcBase } from './abstracts/szGrpcBase';

// strong typed version of the default abstract options specific to this implementation 
// prevents accidentally passing the wrong type of client to constructor
/** options to initialize SzConfig class */
export interface SzGrpcConfigOptions extends SzGrpcEnvironmentOptions { 
    client?: SzConfigClient,
    definition: string
}

/**
 * SzConfig
 * Access the Senzing Config module via gRPC
 * @group SzGrpcClasses
 * @hideconstructor
 * @class
 */
export class SzGrpcConfig extends SzGrpcBase implements SzConfig {
    private _client: SzConfigClient;
    /** See {@link https://github.com/senzing-garage/knowledge-base/blob/main/lists/senzing-component-ids.md} */
    public productId = "5050";

    /** config definition for this instance of SzConfig */
    private _definition: string;

    get definition(): string {
        return this._definition;
    }
    set definition(value: string) {
        this._definition =  value;
    }

    /** 
     * the client is the grpc client class generated by protoc.
     * Not intended for end-user use. We need these in case we have to re-connect or destroy from {@link: SzGrpcEnvironment} but shouldn't be in the docs.
     * @ignore
     */
    public set client(value: SzConfigClient) {
        this._client = value;
    }
    /** 
     * the client is the grpc client class generated by protoc.
     * Not intended for end-user use. We need these in case we have to re-connect or destroy from {@link: SzGrpcEnvironment} but shouldn't be in the docs.
     * @ignore
     */
    public get client(): SzConfigClient {
        return this._client;
    }

    constructor(parameters: SzGrpcConfigOptions) {
        const { connectionString, credentials, definition, client, grpcOptions, grpcConnectionReadyTimeOut } = parameters;
        super(parameters);

        // assign configDefinition to work with
        this._definition = definition;

        if(client) {
            // if client was passed in use/reuse that
            this._client            = client;
        } else if(connectionString) {
            // otherwise create client from options passed in
            this._client             = new SzConfigClient(
                connectionString ? connectionString : DEFAULT_CONNECTION_STRING, 
                credentials ? credentials : DEFAULT_CREDENTIALS,
                grpcOptions ? grpcOptions : DEFAULT_CHANNEL_OPTIONS
            );
        } else {
            // no client or connection params, throw
            throw new Error(`not enough parameters to initialize`);
        }
    }
    /**
     * Adds a data source to an existing in-memory configuration.
     * @param dataSourceCode Name of data source code to add.
     * @returns {Promise<string>} JSON document listing the newly created data source
     */
    addDataSource(dataSourceCode: string) {
        return new Promise<string>((resolve, reject) => {
            if(!this.client){
                reject(new SzNoGrpcConnectionError());
                return
            }
            this.waitForReady(this.getDeadlineFromNow(), (err) => {
                if(err) {
                    reject( err )
                    return;
                }
                const request = new AddDataSourceRequest();
                request.setConfigDefinition(this.definition);
                request.setDataSourceCode(dataSourceCode);
    
                this.client.addDataSource(request, this._metadata, (err, res: AddDataSourceResponse) => {
                    if(err) {
                        reject( newException(err) )
                        return;
                    }
                    let result = res.getResult();
                    // update config definition with updated result
                    this.definition = res.getConfigDefinition();
                    resolve(result);
                });
            })
        });
    }
    /**
     * Adds multiple data sources to an existing in-memory configuration.
     * @param {string[]} dataSourceCodes 
     * @returns {Promise<string[]>} JSON documents for each datasource listing the newly created data source
     */
    addDataSources(dataSourceCodes: string[]) {
        /** 
         * Attempting to create multiple datasources asynchronously ends up causing a connection closed error.
         * JavaScript/TypeScript does not have a good paradigm for synchronously requesting promises one after the other. 
         * (technically we could use generators but google's protoc generated files do not support ESM which would be required for 
         * using "async" and "await" so that leaves us with recursive function calls). Asking the end user to come up 
         * with that logic on their own might be a bit daunting so I'm providing this convenience method that 
         * handles it for them.
         */
        /** private class used for managing sequential requests */
        let addDataSourcesSequentially = (dataSources: string[], callback?: Function) => {
            let _dataSources    = dataSources;
            let _callback: Function | undefined;
            let _onComplete: Promise<string[]>;
            let _responses: string[] = [];

            // define subs
            let next = () => {
                let dsName = _dataSources.shift();
                if(!dsName || dsName == undefined) {
                    // we're done
                    onComplete();
                    return;
                }
                //return new Promise((resolve, reject) => {
                    this.addDataSource(dsName as string)
                    .then((resp) => {
                        // add response to results
                        _responses.push(resp);
                        // call "getNextRequest" again
                        next();
                    })
                //})
            }
        
            let onComplete = () => {
                // when we're done call this method
                if(_callback) {
                    _callback.call(this, _responses);
                }
            }

            // initialization logic
            if(callback) {
                _callback = callback;
            }
            // set up onComplete promise now that we know the number of requests
            _onComplete = new Promise<string[]>((resolve, reject) => {
                if(_responses.length >= _dataSources.length) {
                    resolve(_responses);
                }
            });
            // if there's a callback attach it to the _onComplete promise chain
            if(callback) {
                _onComplete.then(callback as any)
            }
            // kick off the first request. (recursive method chain)
            if(_dataSources && _dataSources.length > 0) {
                next();
            }
        }
        return new Promise<string[]>((resolve, reject) => {
            let addDataSources = addDataSourcesSequentially(dataSourceCodes, (results: string[], error?: Error | undefined) => {
                if(error) {
                    reject(error);
                }
                resolve(results);
            })
        });
    }

    /**
     * Removes a data source from an existing in-memory configuration.
     * or {@link SzGrpcConfig#importConfig} methods.
     * @param dataSourceCode Name of data source code to delete.
     * @returns {Promise<undefined>} for async flow control
     */
    deleteDataSource(dataSourceCode: string) {
        return new Promise((resolve, reject) => {
            if(!this.client){
                reject(new SzNoGrpcConnectionError());
                return
            }
            this.waitForReady(this.getDeadlineFromNow(), (err) => {
                if(err) {
                    reject( err )
                    return;
                }
                const request = new DeleteDataSourceRequest();
                request.setConfigDefinition(this.definition);
                request.setDataSourceCode(dataSourceCode);

                this.client.deleteDataSource(request, this._metadata, (err, res: DeleteDataSourceResponse) => {
                    if(err) {
                        reject( newException(err) )
                        return;
                    }
                    this.definition = res.getConfigDefinition();
                    //console.log("RESPONSE:\n\r", result);
                    resolve(true);
                });
            });
        });
    }
    /**
     * Returns a JSON document of data sources contained in an in-memory configuration.
     * @returns {Promise<{DSRC_ID: number, DSRC_CODE: string}[]>} containing a JSON document listing all of the data sources.
     */
    getDataSources(): Promise<{DSRC_ID: number, DSRC_CODE: string}[]> {
        return new Promise((resolve, reject) => {
            if(!this.client){
                reject(new SzNoGrpcConnectionError());
                return
            }
            this.waitForReady(this.getDeadlineFromNow(), (err) => {
                if(err) {
                    reject( err )
                    return;
                }

                const request = new GetDataSourcesRequest();
                request.setConfigDefinition(this.definition);
                this.client.getDataSources(request, this._metadata, (err, res: GetDataSourcesResponse) => {
                    if(err) {
                        reject( newException(err) )
                        return;
                    }
                    //console.log("RESPONSE:\n\r", result);
                    let result = res.getResult();
                    try{
                        if(result) {
                            let retValJSON = JSON.parse(result);
                            if(retValJSON && retValJSON['DATA_SOURCES']) {
                                resolve(retValJSON['DATA_SOURCES']);
                            } 
                        }
                    }catch(err) {}
                    resolve(JSON.parse(res.getResult()));
                });
            });
        });
    }
    /**
     * @param configDefinition 
     * @returns {Promise<boolean>}
     */
    verifyConfig(configDefinition?: string) {
        return new Promise((resolve, reject) => {
            if(!this.client){
                reject(new SzNoGrpcConnectionError());
                return
            }
            this.waitForReady(this.getDeadlineFromNow(), (err) => {
                if(err) {
                    reject( err )
                    return;
                }
                const request = new VerifyConfigRequest();
                request.setConfigDefinition(configDefinition ? configDefinition : this.definition);
                this.client.verifyConfig(request, this._metadata, (err, res: VerifyConfigResponse) => {
                    if(err) {
                        reject( newException(err) )
                        return;
                    }
                    resolve(res.getResult());
                });
            });
        });
    }
}