name: Publish documentation

on:
  push:
    branches: [main]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    outputs:
      status: ${{ job.status }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v5

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build documentation
        id: build-documentation
        run: npm run build:docs

      - name: Upload static files as artifact
        id: upload-documentation
        uses: actions/upload-pages-artifact@v4
        with:
          path: "docs/"

  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    outputs:
      status: ${{ job.status }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  slack-notification:
    needs: [build, publish]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.build.outputs.status) && contains(fromJSON('["failure", "cancelled"]'), needs.publish.outputs.status) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v3
    with:
      job-status: ${{ needs.build.outputs.status && needs.publish.outputs.status }}
